# Generated by Django 2.1 on 2018-11-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20181115_0505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
    ]
