# Generated by Django 2.1 on 2018-11-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_auto_20181115_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='isVerified',
        ),
    ]
