# Generated by Django 2.1 on 2018-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_remove_userinfo_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='confirmed_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(blank=True, choices=[('---', '---'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR')], default='', max_length=2),
        ),
    ]
