# Generated by Django 2.1 on 2018-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20181115_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userID',
        ),
    ]
