# Generated by Django 2.1 on 2018-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_remove_userinfo_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='confirmed_account',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
