# Generated by Django 2.1.3 on 2018-11-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0008_auto_20181120_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
    ]
