# Generated by Django 2.1.3 on 2018-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('releaseDate', models.CharField(blank=True, default='', max_length=50)),
                ('director', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.CharField(blank=True, default='', max_length=550)),
                ('poster', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
