# Generated by Django 2.1.3 on 2018-12-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
