# Generated by Django 2.1.3 on 2018-12-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20181202_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='modelType',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
