# Generated by Django 2.1.3 on 2018-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieinfo_modeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='modelType',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
