# Generated by Django 2.1.3 on 2018-12-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAccount', '0012_auto_20181202_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cardNumber', models.CharField(blank=True, default='0000', max_length=50)),
                ('cardMonth', models.CharField(blank=True, default='0000', max_length=50)),
                ('cardYear', models.CharField(blank=True, default='0000', max_length=50)),
                ('cardPin', models.CharField(blank=True, default='0000', max_length=50)),
                ('cardFirstName', models.CharField(blank=True, default='', max_length=50)),
                ('cardLastName', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotionCode', models.CharField(blank=True, default='', max_length=50)),
                ('discountPercentage', models.CharField(blank=True, default='00', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(blank=True, default='', max_length=50)),
                ('ticketPrice', models.CharField(blank=True, default='00', max_length=20)),
            ],
        ),
    ]
