# Generated by Django 2.1.3 on 2018-12-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0012_auto_20181202_2126'),
        ('paymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('adultTicket', models.CharField(blank=True, default='', max_length=50)),
                ('childTicket', models.CharField(blank=True, default='', max_length=50)),
                ('seniorTicket', models.CharField(blank=True, default='', max_length=50)),
                ('totalSum', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_type', models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False)),
                ('ticket_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userAccount',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='id',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promotionCode',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
